// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WanderHub_ResortAPI.Data;

#nullable disable

namespace WanderHub_ResortAPI.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WanderHub_ResortAPI.Models.Resort", b =>
                {
                    b.Property<int>("ResortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResortId"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<string>("ResortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateddDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ResortId");

                    b.ToTable("Resort");

                    b.HasData(
                        new
                        {
                            ResortId = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 20, 21, 42, 31, 689, DateTimeKind.Local).AddTicks(150),
                            Details = "A serene getaway blending luxury and nature, perfect for relaxation and adventure.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa3.jpg",
                            Occupancy = 4,
                            Rate = 200.0,
                            ResortName = "Mountain Retreat",
                            Sqft = 550,
                            UpdateddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ResortId = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 20, 21, 42, 31, 689, DateTimeKind.Local).AddTicks(162),
                            Details = "A serene getaway blending luxury and nature, perfect for relaxation and adventure.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa1.jpg",
                            Occupancy = 4,
                            Rate = 300.0,
                            ResortName = "Sunny Beach Resort",
                            Sqft = 550,
                            UpdateddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ResortId = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 20, 21, 42, 31, 689, DateTimeKind.Local).AddTicks(189),
                            Details = "A serene getaway blending luxury and nature, perfect for relaxation and adventure.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa4.jpg",
                            Occupancy = 4,
                            Rate = 400.0,
                            ResortName = "Luxury Forest Oasis",
                            Sqft = 750,
                            UpdateddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ResortId = 4,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 20, 21, 42, 31, 689, DateTimeKind.Local).AddTicks(191),
                            Details = "A serene getaway blending luxury and nature, perfect for relaxation and adventure.",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa5.jpg",
                            Occupancy = 4,
                            Rate = 550.0,
                            ResortName = "Royal Desert Villa",
                            Sqft = 900,
                            UpdateddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ResortId = 5,
                            Amenity = "",
                            CreatedDate = new DateTime(2024, 9, 20, 21, 42, 31, 689, DateTimeKind.Local).AddTicks(193),
                            Details = "A serene getaway blending luxury and nature, perfect for relaxation and adventure..",
                            ImageUrl = "https://dotnetmasteryimages.blob.core.windows.net/bluevillaimages/villa2.jpg",
                            Occupancy = 4,
                            Rate = 600.0,
                            ResortName = "Diamond Pool Resort",
                            Sqft = 1100,
                            UpdateddDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
